import type {
  CameraControllerClassNameSlot,
  CameraControllerLabels,
  CameraControllerModeOption,
  CameraModeConfig,
} from './types';
import type { CameraType } from '../../core/types';

export const CAMERA_CONTROLLER_DEFAULT_MODES: CameraModeConfig[] = [
  { value: 'thirdPerson', label: 'Third Person' },
  { value: 'firstPerson', label: 'First Person' },
  { value: 'chase', label: 'Chase' },
  { value: 'topDown', label: 'Top Down' },
  { value: 'isometric', label: 'Isometric' },
  { value: 'sideScroll', label: 'Side-Scroller' },
  { value: 'fixed', label: 'Fixed' },
];
export const CAMERA_CONTROLLER_DEFAULT_LABELS: CameraControllerLabels = {
  title: 'Camera Mode',
};
export const CAMERA_CONTROLLER_MODE_OPTIONS: Record<CameraType, CameraControllerModeOption> = {
  thirdPerson: {
    xDistance: 15,
    yDistance: 8,
    zDistance: 15,
    fov: 75,
    enableCollision: true,
    enableZoom: true,
    zoom: 1,
    smoothing: { position: 0.1, rotation: 0.1, fov: 0.1 },
  },
  firstPerson: {
    xDistance: 0,
    yDistance: 2,
    zDistance: 0.45,
    fov: 75,
    enableCollision: false,
    enableZoom: false,
    zoom: 1,
    smoothing: { position: 0.2, rotation: 0.15, fov: 0.1 },
  },
  chase: {
    xDistance: 10,
    yDistance: 5,
    zDistance: 10,
    fov: 70,
    enableCollision: true,
    enableZoom: true,
    zoom: 1,
    smoothing: { position: 0.15, rotation: 0.1, fov: 0.1 },
  },
  topDown: {
    xDistance: 0,
    yDistance: 52,
    zDistance: 0,
    fov: 52,
    enableCollision: false,
    enableZoom: true,
    zoom: 1,
    minZoom: 0.3,
    maxZoom: 2.8,
    zoomSpeed: 0.001,
    smoothing: { position: 0.14, rotation: 0.14, fov: 0.14 },
  },
  isometric: {
    xDistance: 15,
    yDistance: 15,
    zDistance: 15,
    fov: 60,
    enableCollision: false,
    enableZoom: true,
    zoom: 1,
    smoothing: { position: 0.1, rotation: 0.1, fov: 0.1 },
  },
  sideScroll: {
    xDistance: 0,
    yDistance: 5,
    zDistance: 18,
    fov: 75,
    enableCollision: false,
    enableZoom: true,
    zoom: 1,
    smoothing: { position: 0.08, rotation: 0.1, fov: 0.1 },
  },
  fixed: {
    xDistance: 0,
    yDistance: 0,
    zDistance: 0,
    fov: 75,
    enableCollision: false,
    enableZoom: false,
    zoom: 1,
    smoothing: { position: 0, rotation: 0, fov: 0 },
  },
};
export const CAMERA_CONTROLLER_DEFAULT_CLASSES: Record<CameraControllerClassNameSlot, string> = {
  root: 'camera-controller-panel',
  floatingRoot: 'camera-controller-panel--floating',
  compactRoot: 'camera-controller-panel--compact',
  header: 'camera-controller-panel-header',
  title: 'camera-controller-panel-title',
  list: 'camera-controller-panel-list',
  modeButton: 'camera-controller-panel-mode',
  activeModeButton: 'camera-controller-panel-mode--active',
  modeIcon: 'camera-controller-panel-mode-icon',
  modeLabel: 'camera-controller-panel-mode-label',
};
