import * as THREE from 'three';
import { NPCNetworkNode, NetworkMessage, NetworkGroup } from '../types';
import { PerformanceMetrics, NetworkEvent } from './types';
export declare class NPCNetworkManager {
    private nodes;
    private groups;
    private eventCallbacks;
    private performanceMetrics;
    private proximityRange;
    private maxDistance;
    private groupIdCounter;
    private maxMessageQueueSize;
    private gridCellSize;
    private grid;
    private nodeCellKey;
    private scratchNearbyNodeIds;
    private scratchDisconnectIds;
    private scratchCenter;
    constructor(proximityRange?: number, maxDistance?: number, maxMessageQueueSize?: number);
    registerNode(npcId: string, position: THREE.Vector3, options?: {
        communicationRange?: number;
        signalStrength?: number;
    }): NPCNetworkNode;
    unregisterNode(npcId: string): boolean;
    updateNodePosition(npcId: string, position: THREE.Vector3): boolean;
    connectNodes(npcIdA: string, npcIdB: string): boolean;
    disconnectNodes(npcIdA: string, npcIdB: string): boolean;
    private disconnectAllConnections;
    private updateProximityConnections;
    private resolveNodeId;
    private getCellKey;
    private addToGrid;
    private removeFromGrid;
    private updateGridPosition;
    private collectNearbyNodeIdsByPosition;
    private getNearbyNodeIds;
    private enqueueMessage;
    sendMessage(message: NetworkMessage): boolean;
    private sendDirectMessage;
    private broadcastMessage;
    private sendGroupMessage;
    getMessages(npcId: string): NetworkMessage[];
    createGroup(type: NetworkGroup['type'], options?: {
        maxMembers?: number;
        range?: number;
        persistent?: boolean;
    }): NetworkGroup;
    joinGroup(npcId: string, groupId: string): boolean;
    leaveGroup(npcId: string, groupId: string): boolean;
    private leaveAllGroups;
    updateProximityGroups(): void;
    addEventListener(eventType: NetworkEvent['type'], callback: (event: NetworkEvent) => void): void;
    removeEventListener(eventType: NetworkEvent['type'], callback: (event: NetworkEvent) => void): void;
    private emitEvent;
    private getTotalConnections;
    getPerformanceMetrics(): PerformanceMetrics;
    getNode(npcId: string): NPCNetworkNode | null;
    getAllNodes(): NPCNetworkNode[];
    forEachNode(callback: (node: NPCNetworkNode) => void): void;
    getGroup(groupId: string): NetworkGroup | null;
    getAllGroups(): NetworkGroup[];
    forEachGroup(callback: (group: NetworkGroup) => void): void;
    clear(): void;
    updateSettings(proximityRange?: number, maxDistance?: number): void;
    getNetworkStats(): {
        nodeCount: number;
        connectionCount: number;
        groupCount: number;
        averageConnections: number;
        totalMessages: number;
    };
}
