import { PlayerState } from '../types';
type PlayerNetworkLogLevel = 'none' | 'error' | 'warn' | 'info' | 'debug';
export interface PlayerNetworkManagerOptions {
    url: string;
    roomId: string;
    playerName: string;
    playerColor: string;
    reconnectAttempts?: number;
    reconnectDelay?: number;
    pingInterval?: number;
    sendRateLimit?: number;
    offlineQueueSize?: number;
    enableAck?: boolean;
    reliableTimeout?: number;
    reliableRetryCount?: number;
    logLevel?: PlayerNetworkLogLevel;
    logToConsole?: boolean;
    onConnect?: () => void;
    onDisconnect?: () => void;
    onWelcome?: (localPlayerId: string, roomState?: Record<string, PlayerState>) => void;
    onPlayerJoin?: (playerId: string, state: PlayerState) => void;
    onPlayerUpdate?: (playerId: string, state: PlayerState) => void;
    onPlayerLeave?: (playerId: string) => void;
    onChat?: (playerId: string, text: string, timestamp: number) => void;
    onPing?: (rttMs: number) => void;
    onReliableFailed?: (info: {
        ackId: string;
        messageType: string;
    }) => void;
    onError?: (error: string) => void;
}
export declare class PlayerNetworkManager {
    private ws;
    private url;
    private roomId;
    private playerName;
    private playerColor;
    private players;
    private localPlayerId;
    private isConnected;
    private isConnecting;
    private logLevel;
    private logToConsole;
    private reconnectAttemptsMax;
    private reconnectDelayMs;
    private reconnectAttemptsUsed;
    private reconnectTimer;
    private shouldReconnect;
    private pingIntervalMs;
    private pingTimer;
    private lastPingSentAt;
    private updateRateLimitMs;
    private lastUpdateSentAt;
    private pendingUpdate;
    private updateFlushTimer;
    private offlineQueueSize;
    private pendingChats;
    private enableAck;
    private reliableTimeoutMs;
    private reliableRetryCount;
    private ackIdCounter;
    private pendingAcks;
    private onConnect?;
    private onDisconnect?;
    private onWelcome?;
    private onPlayerJoin?;
    private onPlayerUpdate?;
    private onPlayerLeave?;
    private onChat?;
    private onPing?;
    private onReliableFailed?;
    private onError?;
    constructor(options: PlayerNetworkManagerOptions);
    private shouldLog;
    private debug;
    private info;
    private warn;
    private error;
    getConnectionStatus(): boolean;
    connect(): void;
    disconnect(): void;
    updateLocalPlayer(state: Partial<PlayerState>): void;
    sendChat(text: string, options?: {
        range?: number;
    }): void;
    private handleServerMessage;
    setCallbacks(callbacks: {
        onConnect?: () => void;
        onDisconnect?: () => void;
        onWelcome?: (localPlayerId: string, roomState?: Record<string, PlayerState>) => void;
        onPlayerJoin?: (playerId: string, state: PlayerState) => void;
        onPlayerUpdate?: (playerId: string, state: PlayerState) => void;
        onPlayerLeave?: (playerId: string) => void;
        onChat?: (playerId: string, text: string, timestamp: number) => void;
        onPing?: (rttMs: number) => void;
        onReliableFailed?: (info: {
            ackId: string;
            messageType: string;
        }) => void;
        onError?: (error: string) => void;
    }): void;
    getPlayers(): Map<string, PlayerState>;
    private clearReconnectTimer;
    private startPingLoop;
    private stopPingLoop;
    private clearUpdateFlushTimer;
    private flushOfflineQueue;
    private tryReconnect;
    private nextAckId;
    private sendReliable;
    private trackPendingAck;
    private scheduleAckTimeout;
    private stopAckTimer;
    private ackReceived;
    private pausePendingAcks;
    private resumePendingAcks;
    private clearAllPendingAcks;
}
export {};
