yarnPath: .yarn/releases/yarn-4.9.1.cjs
nodeLinker: pnp
enableTelemetry: false
packageExtensions:
  "@types/react@*":
    dependencies:
      "@types/react-dom": "*"
pnpMode: strict
compressionLevel: mixed 