import type { PlayerProgress, WorldSnapshot } from '../../platform';
export type NetworkAuthorityMessageType = 'game.command' | 'server.event' | 'state.delta' | 'snapshot.world' | 'snapshot.player' | 'snapshot.ack';
export type AuthoritativeSnapshot = WorldSnapshot | PlayerProgress;
export type GameCommand<TPayload = unknown> = {
    version: number;
    commandId: string;
    domain: string;
    action: string;
    actorId: string;
    submittedAt: number;
    payload: TPayload;
    targetId?: string;
    clientSequence?: number;
    expectedRevision?: number;
    traceId?: string;
};
export type ServerEvent<TPayload = unknown> = {
    version: number;
    eventId: string;
    domain: string;
    type: string;
    occurredAt: number;
    payload: TPayload;
    commandId?: string;
    actorId?: string;
    serverRevision?: number;
    traceId?: string;
};
export type StateDeltaOperation = 'set' | 'merge' | 'delete' | 'append' | 'remove';
export type StateDelta<TValue = unknown> = {
    version: number;
    deltaId: string;
    domain: string;
    path: string[];
    op: StateDeltaOperation;
    serverRevision: number;
    changedAt: number;
    entityId?: string;
    commandId?: string;
    value?: TValue;
};
export type SnapshotAck = {
    version: number;
    ackId: string;
    snapshotId: string;
    kind: AuthoritativeSnapshot['kind'];
    acceptedAt: number;
    worldId?: string;
    playerId?: string;
    roomId?: string;
    serverRevision?: number;
    domains?: string[];
};
export type AuthoritativeNetworkPayloadMap = {
    'game.command': GameCommand;
    'server.event': ServerEvent;
    'state.delta': StateDelta;
    'snapshot.world': WorldSnapshot;
    'snapshot.player': PlayerProgress;
    'snapshot.ack': SnapshotAck;
};
export type CreateGameCommandOptions<TPayload = unknown> = {
    domain: string;
    action: string;
    actorId: string;
    payload: TPayload;
    version?: number;
    commandId?: string;
    submittedAt?: number;
    targetId?: string;
    clientSequence?: number;
    expectedRevision?: number;
    traceId?: string;
};
export type CreateServerEventOptions<TPayload = unknown> = {
    domain: string;
    type: string;
    payload: TPayload;
    version?: number;
    eventId?: string;
    occurredAt?: number;
    commandId?: string;
    actorId?: string;
    serverRevision?: number;
    traceId?: string;
};
export type CreateStateDeltaOptions<TValue = unknown> = {
    domain: string;
    path: string[];
    op: StateDeltaOperation;
    serverRevision: number;
    version?: number;
    deltaId?: string;
    changedAt?: number;
    entityId?: string;
    commandId?: string;
    value?: TValue;
};
export type CreateSnapshotAckOptions = {
    snapshotId: string;
    kind: AuthoritativeSnapshot['kind'];
    version?: number;
    ackId?: string;
    acceptedAt?: number;
    worldId?: string;
    playerId?: string;
    roomId?: string;
    serverRevision?: number;
    domains?: string[];
};
export declare function createGameCommand<TPayload = unknown>(options: CreateGameCommandOptions<TPayload>): GameCommand<TPayload>;
export declare function createServerEvent<TPayload = unknown>(options: CreateServerEventOptions<TPayload>): ServerEvent<TPayload>;
export declare function createStateDelta<TValue = unknown>(options: CreateStateDeltaOptions<TValue>): StateDelta<TValue>;
export declare function createSnapshotAck(options: CreateSnapshotAckOptions): SnapshotAck;
