import type { BuildingBlockConfig, PlacedObject, TileGroupConfig, WallGroupConfig } from '../types';
import { type VisibilityIndex } from '../visibility/core';
export declare const RENDER_KIND_TILE = 0;
export declare const RENDER_KIND_WALL = 1;
export declare const RENDER_KIND_OBJECT = 2;
export declare const RENDER_KIND_BLOCK = 3;
export declare const RENDER_SUBKIND_TILE_GENERIC = 0;
export declare const RENDER_SUBKIND_TILE_GRASS = 1;
export declare const RENDER_SUBKIND_TILE_WATER = 2;
export declare const RENDER_SUBKIND_TILE_SAND = 3;
export declare const RENDER_SUBKIND_TILE_SNOWFIELD = 4;
export declare const RENDER_SUBKIND_WALL_GENERIC = 10;
export declare const RENDER_SUBKIND_OBJECT_SAKURA = 20;
export declare const RENDER_SUBKIND_OBJECT_FLAG = 21;
export declare const RENDER_SUBKIND_OBJECT_FIRE = 22;
export declare const RENDER_SUBKIND_OBJECT_BILLBOARD = 23;
export declare const RENDER_SUBKIND_OBJECT_MODEL = 24;
export declare const RENDER_SUBKIND_BLOCK_GENERIC = 30;
export type BuildingRenderSnapshot = {
    version: number;
    ids: string[];
    kinds: Uint8Array;
    subKinds: Uint8Array;
    centerX: Float32Array;
    centerY: Float32Array;
    centerZ: Float32Array;
    radius: Float32Array;
    cellX: Int16Array;
    cellZ: Int16Array;
    memberCount: Uint16Array;
};
export declare function createEmptyRenderSnapshot(): BuildingRenderSnapshot;
export declare function buildBuildingRenderSnapshot(args: {
    wallGroups: WallGroupConfig[];
    tileGroups: TileGroupConfig[];
    objects: PlacedObject[];
    blocks?: BuildingBlockConfig[];
    version: number;
}): BuildingRenderSnapshot;
export declare function buildVisibilityIndexFromRenderSnapshot(snapshot: BuildingRenderSnapshot): VisibilityIndex;
