export {
  buildingCellToWorld,
  blockToPlacementEntry,
  createBuildingPlacementEngine,
  buildingGroupsToPlacementEntries,
  buildingGridAdapter,
  buildingPlacementAdapter,
  edgeKey,
  edgeSideToWallRotation,
  edgeToWallTransform,
  getTileSupportHeight,
  hasTileCollision,
  hasWallCollision,
  indexAabb,
  pair,
  queryAabbIds,
  snapBuildingPosition,
  cellToTilePosition,
  createBlockFootprint,
  createTileFootprint,
  tileGroupToPlacementEntries,
  tileFootprintKeys,
  tileHalfSize,
  tileOverlaps,
  tilePositionToCell,
  tileToPlacementEntry,
  unindexId,
  wallGroupToPlacementEntries,
  wallToPlacementEntry,
  wallTransformToEdge,
  worldToBuildingCell,
  zigZag,
  normalizeQuarterTurnRotation,
} from './placement';
export type {
  BuildingPlacementCoord,
  BuildingPlacementEngineOptions,
  TileMeta,
  WallMeta,
} from './placement';
