import type { CharacterMenuClassNameSlot } from './types';

export const CHARACTER_MENU_DEFAULT_CLASSES: Record<CharacterMenuClassNameSlot, string> = {
  root: 'character-menu-root',
  backdrop: 'character-menu-backdrop',
  panel: 'character-menu-panel',
  header: 'character-menu-header',
  title: 'character-menu-title',
  actions: 'character-menu-actions',
  iconButton: 'character-menu-button character-menu-button--icon',
  primaryButton: 'character-menu-button character-menu-button--primary',
  ghostButton: 'character-menu-button character-menu-button--ghost',
  body: 'character-menu-body',
  previewSection: 'character-menu-preview',
  previewFrame: 'character-menu-preview-frame',
  previewGlyph: 'character-menu-preview-glyph',
  previewControls: 'character-menu-preview-controls',
  previewControlGroup: 'character-menu-preview-control-group',
  controls: 'character-menu-controls',
  section: 'character-menu-section',
  sectionStack: 'character-menu-section-stack',
  sectionTitle: 'character-menu-section-title',
  input: 'character-menu-input',
  optionRow: 'character-menu-option-row',
  chip: 'character-menu-chip',
  activeChip: 'character-menu-chip character-menu-chip--active',
  colorGrid: 'character-menu-color-grid',
  colorRow: 'character-menu-color-row',
  colorLabel: 'character-menu-color-label',
  colorInput: 'character-menu-color-input',
  filterRow: 'character-menu-filter-row',
  filterLabel: 'character-menu-filter-label',
  checkbox: 'character-menu-checkbox',
  range: 'character-menu-range',
  slotList: 'character-menu-slot-list',
  slot: 'character-menu-slot',
  slotHeader: 'character-menu-slot-header',
  slotTitle: 'character-menu-slot-title',
  assetGrid: 'character-menu-asset-grid',
  assetButton: 'character-menu-asset-button',
  activeAssetButton: 'character-menu-asset-button character-menu-asset-button--active',
  assetImage: 'character-menu-asset-image',
  assetInitial: 'character-menu-asset-initial',
  assetName: 'character-menu-asset-name',
  emptyState: 'character-menu-empty-state',
  closeUpOverlay: 'character-menu-close-up-overlay',
  footer: 'character-menu-footer',
};
