import type { AssetRecord } from '../../../../assets';
export declare function useBuildingPanelState(): {
    editMode: "object" | "tile" | "wall" | "none" | "world" | "block" | "npc";
    setEditMode: (mode: import("../../../..").BuildingSystemState["editMode"]) => void;
    selectedWallId: string | null;
    selectedTileId: string | null;
    selectedBlockId: string | null;
    selectedWallGroupId: string | undefined;
    hoverPosition: import("../../../..").Position3D | null;
    currentTileMultiplier: number;
    setTileMultiplier: (multiplier: number) => void;
    currentTileHeight: number;
    setTileHeight: (height: number) => void;
    currentTileShape: import("../../../..").TileShapeType;
    setTileShape: (shape: import("../../../..").TileShapeType) => void;
    currentTileRotation: number;
    setTileRotation: (rotation: number) => void;
    currentTileMaterialId: string | null;
    setCurrentTileMaterialId: (materialId: string | null) => void;
    currentCustomTileName: string;
    currentCustomTileColor: string;
    currentCustomTileTextureUrl: string;
    setCustomTileDraft: (draft: Partial<{
        name: string;
        color: string;
        textureUrl: string;
    }>) => void;
    applyTilePreset: (presetId: string) => void;
    applyCustomTile: () => void;
    currentWallRotation: number;
    setWallRotation: (rotation: number) => void;
    currentWallKind: import("../../../..").BuildingWallKind;
    setWallKind: (kind: import("../../../..").BuildingWallKind) => void;
    applyWallPreset: (presetId: string) => void;
    selectedTileObjectType: import("../../../..").TileObjectType;
    setSelectedTileObjectType: (type: import("../../../..").TileObjectType) => void;
    currentTerrainColor: string;
    currentTerrainAccentColor: string;
    setTerrainColors: (color: string, accentColor?: string) => void;
    selectedPlacedObjectType: "none" | import("../../../..").PlacedObjectType;
    setSelectedPlacedObjectType: (type: import("../../../..").PlacedObjectType | "none") => void;
    selectedModelObjectId: string;
    setSelectedModelObjectId: (id: string) => void;
    currentModelUrl: string;
    setModelUrl: (url: string) => void;
    currentModelScale: number;
    setModelScale: (scale: number) => void;
    currentModelColor: string;
    setModelColor: (color: string) => void;
    snapToGrid: boolean;
    setSnapToGrid: (snap: boolean) => void;
    currentFlagWidth: number;
    currentFlagHeight: number;
    currentFlagImageUrl: string;
    setFlagWidth: (width: number) => void;
    setFlagHeight: (height: number) => void;
    setFlagImageUrl: (url: string) => void;
    currentFlagStyle: import("../../../..").FlagStyle;
    setFlagStyle: (style: import("../../../..").FlagStyle) => void;
    currentFireIntensity: number;
    currentFireWidth: number;
    currentFireHeight: number;
    currentFireColor: string;
    setFireIntensity: (intensity: number) => void;
    setFireWidth: (width: number) => void;
    setFireHeight: (height: number) => void;
    setFireColor: (color: string) => void;
    currentObjectRotation: number;
    setObjectRotation: (rotation: number) => void;
    selectedTileGroupId: string | undefined;
    tileGroups: Map<string, import("../../../..").TileGroupConfig>;
    wallGroups: Map<string, import("../../../..").WallGroupConfig>;
    meshes: Map<string, import("../../../..").MeshConfig>;
    addMesh: (mesh: import("../../../..").MeshConfig) => void;
    updateMesh: (id: string, updates: Partial<import("../../../..").MeshConfig>) => void;
    updateWall: (groupId: string, wallId: string, updates: Partial<import("../../../..").WallConfig>) => void;
    updateTile: (groupId: string, tileId: string, updates: Partial<import("../../../..").TileConfig>) => void;
    setCurrentWallMaterialId: (materialId: string | null) => void;
    removeWall: (groupId: string, wallId: string) => void;
    removeTile: (groupId: string, tileId: string) => void;
    removeBlock: (blockId: string) => void;
    currentBillboardText: string;
    currentBillboardImageUrl: string;
    currentBillboardColor: string;
    currentBillboardWidth: number;
    currentBillboardHeight: number;
    currentBillboardScale: number;
    currentBillboardOffsetY: number;
    currentBillboardElevation: number;
    currentBillboardIntensity: number;
    setBillboardText: (text: string) => void;
    setBillboardImageUrl: (url: string) => void;
    setBillboardColor: (color: string) => void;
    setBillboardWidth: (width: number) => void;
    setBillboardHeight: (height: number) => void;
    setBillboardScale: (scale: number) => void;
    setBillboardOffsetY: (offsetY: number) => void;
    setBillboardElevation: (elevation: number) => void;
    setBillboardIntensity: (intensity: number) => void;
    currentObjectPrimaryColor: string;
    currentObjectSecondaryColor: string;
    currentTreeKind: import("../../../..").BuildingTreeKind;
    setObjectPrimaryColor: (color: string) => void;
    setObjectSecondaryColor: (color: string) => void;
    setTreeKind: (kind: import("../../../..").BuildingTreeKind) => void;
    showSnow: boolean;
    setShowSnow: (show: boolean) => void;
    showFog: boolean;
    setShowFog: (show: boolean) => void;
    fogColor: string;
    setFogColor: (color: string) => void;
    weatherEffect: import("../../../..").BuildingWeatherEffect;
    setWeatherEffect: (effect: import("../../../..").BuildingWeatherEffect) => void;
    npcInstances: Map<string, import("../../../../npc/types").NPCInstance>;
    npcBrainBlueprints: Map<string, import("../../../..").NPCBrainBlueprint>;
    selectedNPCTemplateId: string | undefined;
    selectedNPCInstanceId: string | undefined;
    setSelectedNPCTemplate: (id: string) => void;
    setSelectedNPCInstance: (id: string) => void;
    updateNPCInstance: (id: string, updates: Partial<import("../../../../npc/types").NPCInstance>) => void;
    setNPCNavigation: (instanceId: string, waypoints: [number, number, number][], speed?: number) => void;
    clearNPCNavigation: (instanceId: string) => void;
    updateNPCBehavior: (instanceId: string, behavior: Partial<import("../../../..").NPCBehaviorConfig>) => void;
    updateNPCBrain: (instanceId: string, brain: Partial<import("../../../..").NPCBrainConfig>) => void;
    updateNPCPerception: (instanceId: string, perception: Partial<import("../../../..").NPCPerceptionConfig>) => void;
    addNPCBrainBlueprint: (blueprint: import("../../../..").NPCBrainBlueprint) => void;
    updateNPCBrainBlueprint: (id: string, updates: Partial<import("../../../..").NPCBrainBlueprint>) => void;
    initializeNPCDefaults: () => void;
    buildingAssets: AssetRecord[];
    npcTemplatesArray: import("../../../..").NPCTemplate[];
    npcInstancesArray: import("../../../../npc/types").NPCInstance[];
    npcAnimationsArray: import("../../../..").NPCAnimation[];
    npcBrainBlueprintsArray: import("../../../..").NPCBrainBlueprint[];
};
