import * as THREE from 'three';
import type { RefObject } from '@core/boilerplate';
import { PhysicsConfigType } from '@stores/slices';
import { type InputAdapter } from '../../../interactions/core';
import { PhysicsCalcProps, PhysicsState } from '../../types';
export declare class DirectionComponent {
    private memoManager;
    private vectorCache;
    private lastEulerY;
    private lastDirectionLength;
    private lastKeyboardState;
    private timers;
    private inputBackend;
    private config;
    private tempEuler;
    private tempQuaternion;
    private targetQuaternion;
    private cameraForward;
    private cameraRight;
    private desiredMovement;
    private nextMousePosition;
    private readonly upAxis;
    constructor(config?: PhysicsConfigType, inputBackend?: InputAdapter);
    updateDirection(physicsState: PhysicsState, controlMode?: string, calcProp?: PhysicsCalcProps, innerGroupRef?: RefObject<THREE.Group>): void;
    private updateCharacterDirection;
    private updateVehicleDirection;
    private updateAirplaneDirection;
    private getKeyboard;
    private getMouse;
    private applyAirplaneRotation;
    private handleMouseDirection;
    private syncClickNavigationTarget;
    private handleClicker;
    private applyMouseRotation;
    private handleKeyboardDirection;
    private resolveKeyboardMovementDirection;
    private emitRotationUpdate;
    dispose(): void;
}
