import 'reflect-metadata'
import './core/initializeBridges';

export * from './blueprints';
export * from './core/assets';
export * from './core/content';
export * from './core/editor';
export * from './core/gameplay';
export * from './core/grid';
export * from './core/networks/adapter';
export * from './core/ops';
export * from './core/platform';
export * from './core/placement';
export * from './core/plugins';
export * from './core/runtime';
export {
  GaesupWorld,
  GaesupController,
  // Animation
  
  AnimationDebugPanel,
  // Camera
  Camera,
  CameraDebugPanel,
  CameraPresets,
  // Motions
  MotionController,
  MotionDebugPanel,
  MotionUI,
  Teleport,
  usePlayerPosition,
  useStateSystem,
  // Interaction
  Clicker,
  Gamepad,
  GroundClicker,
  // World
  World,
  WorldContainer,
  WorldConfigProvider,
  // UI
  SpeechBalloon,
  // Networks (multiplayer)
  useMultiplayer,
  usePlayerNetwork,
  useNetworkBridge,
  useNetworkMessage,
  useNetworkGroup,
  useNetworkStats,
  useNPCConnection,
  defaultMultiplayerConfig,
  MultiplayerCanvas,
  RemotePlayer,
  ConnectionForm,
  PlayerInfoOverlay,
  // Building
  V3,
  V30,
  V31,
  MiniMap,
  MinimapPlatform,
  BuildingSystem,
  TileSystem,
  WallSystem,
  BuildingUI,
  GridHelper,
  useGaesupController,
  useTeleport,
  useBuildingEditor,
  useBuildingStore,
  BUILDING_WALL_KIND_OPTIONS,
  BUILDING_WALL_PRESETS,
  BUILDING_TILE_PRESETS,
  BUILDING_TREE_COLOR_PRESETS,
  BUILDING_TREE_OPTIONS,
  BUILDING_WEATHER_EFFECT_OPTIONS,
  BuildingController,
  createBuildingPlugin,
  buildingPlugin,
  Editor,
  FocusableObject,
  GaeSupProps,
  GaesupWorldContent,
  useGaesupStore,
  // NPC
  NPCInstance,
  NPCPreview,
  NPCEventEditor,
  NPCSystem,
  useNPCStore,
  createNPCObservation,
  resolveNPCBrainDecision,
  registerNPCBrainAdapter,
  configureReinforcementAdapter,
  getReinforcementAdapterConfig,
  registerDefaultReinforcementAdapter,
  compileNPCBrainBlueprint,
  getNPCBrainBlueprint,
  registerNPCBrainBlueprint,
  unregisterNPCBrainBlueprint,
  // Environment meshes
  Sakura,
  SakuraBatch,
  Sand,
  SandBatch,
  Snowfield,
  SnowfieldBatch,
  Snow,
  Grass,
  GrassDriver,
  getGrassManager,
  Water,
  Billboard,
  Fire,
  // Toon
  createToonMaterial,
  getToonGradient,
  setDefaultToonMode,
  getDefaultToonMode,
  disposeToonGradients,
  applyToonToScene,
  // Time
  TimeHUD,
  useTimeStore,
  useGameClock,
  useGameTime,
  useTimeOfDay,
  useDayChange,
  useHourChange,
  // Save
  getSaveSystem,
  createDefaultSaveSystem,
  SaveSystem,
  IndexedDBAdapter,
  LocalStorageAdapter,
  useAutoSave,
  useLoadOnMount,
  // Items
  getItemRegistry,
  registerSeedItems,
  SEED_ITEMS,
  // Inventory
  useInventoryStore,
  useInventory,
  useEquippedItem,
  useHotbar,
  useHotbarKeyboard,
  HotbarUI,
  InventoryUI,
  // Interactions (new)
  Interactable,
  InteractionPrompt,
  InteractionTracker,
  useInteractablesStore,
  useCurrentInteraction,
  useInteractionKey,
  // Toast / Notification
  ToastHost,
  useToastStore,
  notify,
  // Economy
  useWalletStore,
  useShopStore,
  WalletHUD,
  ShopUI,
  // Dialog
  DialogRunner,
  useDialogStore,
  getDialogRegistry,
  DialogBox,
  // Tools
  ToolUseController,
  getToolEvents,
  useToolUse,
  useEquippedToolKind,
  // World objects
  TreeObject,
  FishSpot,
  BugSpot,
  // NPC scheduler
  getNPCScheduler,
  resolveSchedule,
  useNpcSchedule,
  // Farming
  getCropRegistry,
  usePlotStore,
  CropPlot,
  registerSeedCrops,
  // Weather
  useWeatherStore,
  useWeatherTicker,
  WeatherHUD,
  WeatherEffect,
  // Events
  getEventRegistry,
  isEventActive,
  useEventsStore,
  useEventsTicker,
  EventsHUD,
  registerSeedEvents,
  // Town
  useTownStore,
  useDecorationScore,
  HousePlot,
  TownHUD,
  // Audio
  getAudioEngine,
  useAudioStore,
  useAmbientBgm,
  AudioControls,
  Footsteps,
  // Character
  useCharacterStore,
  CharacterCreator,
  OutfitAvatar,
  useAssetStore,
  AssetPreviewCanvas,
  SEED_ASSETS,
  HttpAssetSource,
  resolveCharacterParts,
  // Effects
  Footprints,
  // i18n
  LOCALE_LABEL,
  useI18nStore,
  useTranslate,
  useLocale,
  t,
  // Input
  TouchControls,
  // Perf
  usePerfStore,
  detectCapabilities,
  autoDetectProfile,
  profileForTier,
  classifyTier,
  // Rendering polish
  DynamicFog,
  DynamicSky,
  // Scene / dimensions
  useSceneStore,
  SceneFader,
  SceneRoot,
  HouseDoor,
  useRoomVisibilityStore,
  RoomRoot,
  RoomPortal,
  RoomVisibilityDriver,
  // Relations
  useFriendshipStore,
  FRIENDSHIP_LEVELS,
  DAILY_FRIENDSHIP_CAP,
  // Quests
  getQuestRegistry,
  useQuestStore,
  useQuestObjectiveTracker,
  QuestLogUI,
  // Mail
  useMailStore,
  MailboxUI,
  // Catalog
  useCatalogStore,
  useCatalogTracker,
  CatalogUI,
  CATALOG_CATEGORIES,
  // Crafting
  getRecipeRegistry,
  useCraftingStore,
  CraftingUI,
  useUIConfigStore,
} from './core';
export type {
  SakuraTreeEntry,
  SandEntry,
  SnowfieldEntry,
  GameTime,
  Season,
  Weekday,
  CameraOptionType,
  TimeMode,
  TimeSerialized,
  SaveBlob,
  SaveAdapter,
  DomainBinding,
  ItemId,
  ItemDef,
  ItemCategory,
  ToolKind,
  Rarity,
  Slot,
  InventorySerialized,
  InteractableProps,
  InteractableEntry,
  InteractableKind,
  InteractionPromptProps,
  InteractionTrackerProps,
  CurrentInteraction,
  Toast,
  ToastKind,
  WalletSerialized,
  ShopOffer,
  ShopSerialized,
  WalletHUDProps,
  ShopUIProps,
  DialogTreeId,
  DialogNodeId,
  DialogNode,
  DialogChoice,
  DialogTree,
  DialogContext,
  DialogCondition,
  DialogEffect,
  DialogBoxProps,
  ToolUseEvent,
  ToolUseHandler,
  ToolUseControllerProps,
  TreeObjectProps,
  FishSpotProps,
  BugSpotProps,
  CatchEntry,
  NPCSchedule,
  NPCScheduleEntry,
  NPCActivity,
  ActiveSlot,
  FriendshipLevel,
  FriendshipEntry,
  RelationsSerialized,
  QuestId,
  ObjectiveId,
  QuestObjective,
  QuestReward,
  QuestDef,
  QuestStatus,
  QuestProgress,
  QuestSerialized,
  QuestLogUIProps,
  MailAttachment,
  MailMessage,
  MailSerialized,
  MailboxUIProps,
  CatalogEntry,
  CatalogSerialized,
  CatalogUIProps,
  RecipeId,
  RecipeIngredient,
  RecipeDef,
  CraftingSerialized,
  CraftingUIProps,
  CropId,
  CropStage,
  CropDef,
  PlotState,
  Plot,
  FarmingSerialized,
  CropPlotProps,
  WeatherKind,
  WeatherEntry,
  WeatherSerialized,
  WeatherHUDProps,
  WeatherEffectProps,
  WeatherEffectKind,
  BuildingWallKind,
  BuildingWallPreset,
  BuildingTilePreset,
  BuildingWeatherEffect,
  BuildingTreeKind,
  NPCAction,
  NPCBehaviorConfig,
  NPCBehaviorMode,
  NPCBrainAdapter,
  NPCBrainAdapterContext,
  ReinforcementAdapterConfig,
  NPCBrainBlueprint,
  NPCBrainBlueprintCondition,
  NPCBrainBlueprintEdge,
  NPCBrainBlueprintNode,
  NPCBrainBlueprintTarget,
  NPCBrainConfig,
  NPCBrainDecision,
  NPCBrainMode,
  NPCEvent,
  NPCEventPayload,
  NPCInstance as NPCInstanceData,
  NPCObservation,
  NPCObservationTarget,
  NPCPerceptionConfig,
  NPCVolumeConfig,
  NPCTemplate,
  EventId,
  EventTrigger,
  EventDef,
  EventState,
  EventsSerialized,
  EventsHUDProps,
  ResidentId,
  HouseId,
  Resident,
  HousePlotState,
  HousePlotData,
  HousePlotProps,
  TownStats,
  TownSerialized,
  TownHUDProps,
  DecorationWeights,
  SfxId,
  SfxDef,
  BgmId,
  BgmTrack,
  AudioSerialized,
  AudioControlsProps,
  LocaleId,
  PerfTier,
  AssetKind,
  AssetSlot,
  AssetRecord,
  AssetSource,
  AssetQuery,
  AssetPreviewCanvasProps,
  ResolveCharacterPartsInput,
} from './core';
