import 'reflect-metadata'
import './core/initializeBridges';

export {
  GaesupWorld,
  GaesupController,
  // Animation
  
  AnimationDebugPanel,
  // Camera
  Camera,
  CameraDebugPanel,
  CameraPresets,
  // Motions
  MotionController,
  MotionDebugPanel,
  MotionUI,
  Teleport,
  // Interaction
  Clicker,
  Gamepad,
  GroundClicker,
  // World
  World,
  WorldContainer,
  // UI
  SpeechBalloon,
  // Networks (multiplayer)
  useMultiplayer,
  usePlayerNetwork,
  useNetworkBridge,
  useNetworkMessage,
  useNetworkGroup,
  useNetworkStats,
  useNPCConnection,
  defaultMultiplayerConfig,
  MultiplayerCanvas,
  RemotePlayer,
  ConnectionForm,
  PlayerInfoOverlay,
  // Building
  V3,
  V30,
  V31,
  MiniMap,
  MinimapPlatform,
  BuildingSystem,
  TileSystem,
  WallSystem,
  BuildingUI,
  GridHelper,
  useGaesupController,
  useTeleport,
  useBuildingEditor,
  useBuildingStore,
  BuildingController,
  Editor,
  FocusableObject,
  GaeSupProps,
  GaesupWorldContent,
  useGaesupStore,
  // NPC
  useNPCStore,
  // Environment meshes
  Sakura,
  SakuraBatch,
  Sand,
  SandBatch,
  Snowfield,
  SnowfieldBatch,
  Snow,
  Grass,
  Water,
  Billboard,
  Fire,
  // Toon / Outline
  createToonMaterial,
  getToonGradient,
  setDefaultToonMode,
  getDefaultToonMode,
  disposeToonGradients,
  applyToonToScene,
  ToonOutlines,
  Outlined,
  // Time
  TimeHUD,
  useTimeStore,
  useGameClock,
  useGameTime,
  useTimeOfDay,
  useDayChange,
  useHourChange,
  // Save
  getSaveSystem,
  createDefaultSaveSystem,
  SaveSystem,
  IndexedDBAdapter,
  LocalStorageAdapter,
  useAutoSave,
  useLoadOnMount,
  // Items
  getItemRegistry,
  registerSeedItems,
  SEED_ITEMS,
  // Inventory
  useInventoryStore,
  useInventory,
  useEquippedItem,
  useHotbar,
  useHotbarKeyboard,
  HotbarUI,
  InventoryUI,
  // Interactions (new)
  Interactable,
  InteractionPrompt,
  InteractionTracker,
  useInteractablesStore,
  useCurrentInteraction,
  useInteractionKey,
  // Toast / Notification
  ToastHost,
  useToastStore,
  notify,
  // Economy
  useWalletStore,
  useShopStore,
  WalletHUD,
  ShopUI,
  // Dialog
  DialogRunner,
  useDialogStore,
  getDialogRegistry,
  DialogBox,
  // Tools
  ToolUseController,
  getToolEvents,
  useToolUse,
  useEquippedToolKind,
  // World objects
  TreeObject,
  FishSpot,
  BugSpot,
  // NPC scheduler
  getNPCScheduler,
  resolveSchedule,
  // Relations
  useFriendshipStore,
  FRIENDSHIP_LEVELS,
  DAILY_FRIENDSHIP_CAP,
  // Quests
  getQuestRegistry,
  useQuestStore,
  useQuestObjectiveTracker,
  QuestLogUI,
  // Mail
  useMailStore,
  MailboxUI,
  // Catalog
  useCatalogStore,
  useCatalogTracker,
  CatalogUI,
  CATALOG_CATEGORIES,
  // Crafting
  getRecipeRegistry,
  useCraftingStore,
  CraftingUI,
} from './core';
export type {
  SakuraTreeEntry,
  SandEntry,
  SnowfieldEntry,
  ToonOutlinesProps,
  OutlinedProps,
  GameTime,
  Season,
  Weekday,
  TimeMode,
  TimeSerialized,
  SaveBlob,
  SaveAdapter,
  DomainBinding,
  ItemId,
  ItemDef,
  ItemCategory,
  ToolKind,
  Rarity,
  Slot,
  InventorySerialized,
  InteractableProps,
  InteractableEntry,
  InteractableKind,
  InteractionPromptProps,
  InteractionTrackerProps,
  CurrentInteraction,
  Toast,
  ToastKind,
  WalletSerialized,
  ShopOffer,
  ShopSerialized,
  WalletHUDProps,
  ShopUIProps,
  DialogTreeId,
  DialogNodeId,
  DialogNode,
  DialogChoice,
  DialogTree,
  DialogContext,
  DialogCondition,
  DialogEffect,
  DialogBoxProps,
  ToolUseEvent,
  ToolUseHandler,
  ToolUseControllerProps,
  TreeObjectProps,
  FishSpotProps,
  BugSpotProps,
  CatchEntry,
  NPCSchedule,
  NPCScheduleEntry,
  NPCActivity,
  ActiveSlot,
  FriendshipLevel,
  FriendshipEntry,
  RelationsSerialized,
  QuestId,
  ObjectiveId,
  QuestObjective,
  QuestReward,
  QuestDef,
  QuestStatus,
  QuestProgress,
  QuestSerialized,
  QuestLogUIProps,
  MailAttachment,
  MailMessage,
  MailSerialized,
  MailboxUIProps,
  CatalogEntry,
  CatalogSerialized,
  CatalogUIProps,
  RecipeId,
  RecipeIngredient,
  RecipeDef,
  CraftingSerialized,
  CraftingUIProps,
} from './core';
export { GaesupAdmin } from './admin';
