import { NPCSystemState, NPCTemplate, NPCInstance, NPCCategory, NPCAnimation, NPCPart, NPCVolumeConfig, NPCBrainConfig, NPCPerceptionConfig, NPCBehaviorConfig, NPCAction, NPCObservation, NPCBrainDecision, NPCBrainBlueprint, ClothingSet, ClothingCategory, NPCEvent } from '../types';
interface NPCStore extends NPCSystemState {
    initialized: boolean;
    initializeDefaults: () => void;
    previewAccessories: {
        hat?: string;
        glasses?: string;
    };
    setPreviewAccessory: (type: 'hat' | 'glasses', id: string | undefined) => void;
    addTemplate: (template: NPCTemplate) => void;
    updateTemplate: (id: string, updates: Partial<NPCTemplate>) => void;
    removeTemplate: (id: string) => void;
    addInstance: (instance: NPCInstance) => void;
    updateInstance: (id: string, updates: Partial<NPCInstance>) => void;
    removeInstance: (id: string) => void;
    addCategory: (category: NPCCategory) => void;
    updateCategory: (id: string, updates: Partial<NPCCategory>) => void;
    removeCategory: (id: string) => void;
    addClothingSet: (set: ClothingSet) => void;
    updateClothingSet: (id: string, updates: Partial<ClothingSet>) => void;
    removeClothingSet: (id: string) => void;
    addClothingCategory: (category: ClothingCategory) => void;
    updateClothingCategory: (id: string, updates: Partial<ClothingCategory>) => void;
    removeClothingCategory: (id: string) => void;
    addAnimation: (animation: NPCAnimation) => void;
    updateAnimation: (id: string, updates: Partial<NPCAnimation>) => void;
    removeAnimation: (id: string) => void;
    addBrainBlueprint: (blueprint: NPCBrainBlueprint) => void;
    updateBrainBlueprint: (id: string, updates: Partial<NPCBrainBlueprint>) => void;
    removeBrainBlueprint: (id: string) => void;
    setSelectedTemplate: (id: string) => void;
    setSelectedCategory: (id: string) => void;
    setSelectedInstance: (id: string) => void;
    setSelectedClothingSet: (id: string) => void;
    setSelectedClothingCategory: (id: string) => void;
    setEditMode: (editMode: boolean) => void;
    createInstanceFromTemplate: (templateId: string, position: [number, number, number]) => void;
    updateInstancePart: (instanceId: string, partId: string, updates: Partial<NPCPart>) => void;
    changeInstanceClothing: (instanceId: string, clothingSetId: string) => void;
    updateInstanceVolume: (instanceId: string, volume: Partial<NPCVolumeConfig>) => void;
    updateInstanceBrain: (instanceId: string, brain: Partial<NPCBrainConfig>) => void;
    updateInstancePerception: (instanceId: string, perception: Partial<NPCPerceptionConfig>) => void;
    updateInstanceBehavior: (instanceId: string, behavior: Partial<NPCBehaviorConfig>) => void;
    setInstanceObservation: (instanceId: string, observation: NPCObservation) => void;
    setInstanceDecision: (instanceId: string, decision: NPCBrainDecision) => void;
    executeInstanceAction: (instanceId: string, action: NPCAction) => void;
    executeInstanceActions: (instanceId: string, actions: NPCAction[]) => void;
    addInstanceEvent: (instanceId: string, event: NPCEvent) => void;
    removeInstanceEvent: (instanceId: string, eventId: string) => void;
    setNavigation: (instanceId: string, waypoints: [number, number, number][], speed?: number) => void;
    advanceNavigation: (instanceId: string) => void;
    clearNavigation: (instanceId: string) => void;
    updateNavigationPosition: (instanceId: string, position: [number, number, number]) => void;
}
export declare const useNPCStore: import("zustand").UseBoundStore<Omit<import("zustand").StoreApi<NPCStore>, "setState"> & {
    setState(nextStateOrUpdater: NPCStore | Partial<NPCStore> | ((state: import("immer").WritableDraft<NPCStore>) => void), shouldReplace?: false): void;
    setState(nextStateOrUpdater: NPCStore | ((state: import("immer").WritableDraft<NPCStore>) => void), shouldReplace: true): void;
}>;
export {};
